#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

project="$tmpdir/daily_qa_ops_real_adapters"
cp -R examples/daily_qa_ops "$project"

go build -o "$project/bin/fbt-runner-openai" ./adapters/openai/cmd/fbt-runner-openai
go build -o "$project/bin/fbt-runner-codex-cli" ./adapters/codex-cli/cmd/fbt-runner-codex-cli

cat >"$project/fs_project.yml" <<'YAML'
name: daily_qa_ops_real_adapters
config_version: 1
version: 0.1.0
source_paths: ["sources"]
transform_paths: ["transforms"]
asset_paths: ["assets"]
policy_paths: ["policies"]
eval_paths: ["evals"]
artifact_path: "target/artifacts"
state:
  backend: local
  path: .fbt/state
execution:
  mode: local
runners:
  - name: openai.responses
    type: llm
    protocol: stdio_jsonrpc
    command: bin/fbt-runner-openai
    args: ["responses"]
    cwd: .
    env:
      - OPENAI_API_KEY
      - FBT_OPENAI_ADAPTER_FAKE_RESPONSE
    config:
      provider: openai
      default_model: gpt-5
  - name: codex.cli
    type: agent
    protocol: stdio_jsonrpc
    command: bin/fbt-runner-codex-cli
    cwd: .
    env:
      - FBT_CODEX_CLI_COMMAND
    config:
      provider: openai
      default_model: gpt-5
selectors:
  - name: daily
    definition:
      method: tag
      value: daily_qa
YAML

perl -0pi -e 's/runner: demo\.llm/runner: openai.responses/g; s/provider: demo/provider: openai/g; s/name: deterministic-demo-llm/name: gpt-5/g' "$project/transforms/qa/daily_candidates.yml"
perl -0pi -e 's/runner: demo\.agent/runner: codex.cli/g; s/provider: demo/provider: openai/g; s/name: deterministic-demo-agent/name: gpt-5/g' "$project/transforms/qa/promote_manual.yml"

cat >"$project/policies/qa.yml" <<'YAML'
policies:
  - name: daily_candidate_scope
    read:
      - data/qa/
      - data/reference/
    write:
      - .fbt/work/
      - target/artifacts/qa/
    network: true
    limits:
      timeout_seconds: 120
      max_output_bytes: 200000
  - name: manual_promotion_scope
    read:
      - target/artifacts/qa/
      - data/reference/
    write:
      - .fbt/work/
      - target/artifacts/manual/
    network: true
    limits:
      timeout_seconds: 120
      max_output_bytes: 200000
YAML

if [[ "${FBT_PILOT_LIVE_OPENAI:-0}" != "1" ]]; then
  export OPENAI_API_KEY="${OPENAI_API_KEY:-test}"
  export FBT_OPENAI_ADAPTER_FAKE_RESPONSE="${FBT_OPENAI_ADAPTER_FAKE_RESPONSE:-# Daily QA Candidates\n\nGenerated by the official OpenAI adapter fake-response pilot.}"
elif [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "pilot-daily-real-adapters: OPENAI_API_KEY is required when FBT_PILOT_LIVE_OPENAI=1" >&2
  exit 2
else
  unset FBT_OPENAI_ADAPTER_FAKE_RESPONSE
fi

export FBT_CODEX_CLI_COMMAND="${FBT_CODEX_CLI_COMMAND:-$ROOT_DIR/adapters/codex-cli/testdata/codex-cli-fixture.sh}"
export FBT_BIN="${FBT_BIN:-go run ./cmd/fbt}"
export FBT_PROJECT_DIR="$project"
export FBT_RUN_ID="real-adapter-pilot"

"$project/ops/run-daily.sh" >"$tmpdir/pilot.txt"
grep -q "fbt daily support knowledge run complete" "$tmpdir/pilot.txt"
grep -q "RUNNER_PROTOCOL_OK" "$project/target/ops/runs/real-adapter-pilot/doctor.txt"
grep -q "openai.responses" "$project/target/ops/runs/real-adapter-pilot/doctor.txt"
grep -q "codex.cli" "$project/target/ops/runs/real-adapter-pilot/doctor.txt"
grep -q "PASS    structural_artifacts" "$project/target/ops/runs/real-adapter-pilot/quality-gates.txt"
grep -q "openai.responses" "$project/target/ops/runs/real-adapter-pilot/openlineage.ndjson"
grep -q "codex.cli" "$project/target/ops/runs/real-adapter-pilot/openlineage.ndjson"

echo "production-pilot-smoke: ok"
